patchesJson6902:
  - target:
      version: v1
      group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: gatekeeper-validating-webhook-configuration
    patch: |-
      - op: replace
        path: /webhooks/1/rules/0/scope
        value: [ '*', '*/scale' ]
